# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(default='mock', max_length=50, verbose_name='Provedor de Mapas')),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Origem')),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Origem')),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Destino')),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Destino')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distância Terrestre (KM)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duração da Rota (Minutos)')),
                ('polyline', models.TextField(blank=True, verbose_name='Encoded Polyline da Rota')),
                ('toll_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Estimativa de Pedágios')),
                ('restrictions', models.JSONField(blank=True, default=dict, verbose_name='Restrições Operacionais (Altura/Peso)')),
                ('freight_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_details', to='freight.freightorder', verbose_name='Ordem de Frete')),
            ],
            options={
                'verbose_name': 'Rota do Frete',
                'verbose_name_plural': 'Rotas dos Fretes',
            },
        ),
    ]
