# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Origem')),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Origem')),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Destino')),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Destino')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Tipo de Veículo Recomendado')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distância (KM)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duração (Minutos)')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarifa Base')),
                ('distance_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Distância')),
                ('time_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Tempo')),
                ('helper_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Ajudante')),
                ('insurance_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Seguro')),
                ('urgency_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Urgência')),
                ('risk_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Risco de Rota')),
                ('toll_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Estimativa de Pedágios')),
                ('availability_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Disponibilidade')),
                ('total_estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total Estimado')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='Breakdown Detalhado')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargo.cargotype', verbose_name='Tipo de Carga')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Estimativa de Preço',
                'verbose_name_plural': 'Estimativas de Preços',
                'ordering': ['-created_at'],
            },
        ),
    ]
