# Generated by Django 4.2.30 on 2026-05-31 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('consent_type', models.CharField(choices=[('terms_of_service', 'Termos de Uso'), ('privacy_policy', 'Política de Privacidade')], max_length=50, verbose_name='Tipo de Consentimento')),
                ('accepted', models.BooleanField(default=False, verbose_name='Aceito')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Aceito em')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='Endereço IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Consentimento do Usuário',
                'verbose_name_plural': 'Consentimentos do Usuário',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
