# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('origin_address', models.CharField(max_length=255, verbose_name='Endereço de Origem')),
                ('origin_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Origem')),
                ('origin_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Origem')),
                ('destination_address', models.CharField(max_length=255, verbose_name='Endereço de Destino')),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude de Destino')),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude de Destino')),
                ('cargo_category', models.CharField(choices=[('EQUIPMENTS', 'Equipamentos e Móveis'), ('DRY_GRAINS', 'Grãos Secos')], max_length=30, verbose_name='Categoria Principal da Carga')),
                ('cargo_description', models.TextField(verbose_name='Descrição da Carga')),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Peso Estimado (KG)')),
                ('estimated_volume_m3', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Volume Estimado (M³)')),
                ('required_vehicle_type', models.CharField(max_length=50, verbose_name='Tipo de Veículo Exigido')),
                ('required_body_type', models.CharField(max_length=50, verbose_name='Tipo de Carroceria Exigida')),
                ('requires_helper', models.BooleanField(default=False, verbose_name='Exige Ajudante')),
                ('requires_insurance', models.BooleanField(default=False, verbose_name='Exige Seguro')),
                ('scheduled_pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='Coleta Agendada para')),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distância Estimada (KM)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(verbose_name='Duração Estimada (Minutos)')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Estimado')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Final')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('waiting_driver', 'Aguardando Motorista'), ('driver_found', 'Motorista Encontrado'), ('driver_going_to_pickup', 'Motorista a Caminho da Coleta'), ('arrived_at_origin', 'Chegou na Origem'), ('cargo_collected', 'Carga Coletada'), ('in_transit', 'Em Trânsito'), ('temporarily_stopped', 'Parado Temporariamente'), ('route_deviation_detected', 'Desvio de Rota Identificado'), ('near_destination', 'Próximo ao Destino'), ('arrived_at_destination', 'Chegou ao Destino'), ('delivered', 'Entregue'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado'), ('disputed', 'Em Disputa')], default='requested', max_length=30, verbose_name='Status do Frete')),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Chegada (ETA)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Coletado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de Cancelamento')),
                ('carrier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_orders', to='companies.carriercompany', verbose_name='Transportadora')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_orders_as_customer', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Embarcador')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_orders_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_orders', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Frete',
                'verbose_name_plural': 'Ordens de Fretes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Peso Estimado (KG)')),
                ('estimated_volume_m3', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Volume Estimado (M³)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Frágil')),
                ('requires_helper', models.BooleanField(default=False, verbose_name='Requer Ajudante')),
                ('requires_insurance', models.BooleanField(default=False, verbose_name='Requer Seguro')),
                ('requires_covered_vehicle', models.BooleanField(default=False, verbose_name='Requer Veículo Coberto / Baú')),
                ('requires_grain_body', models.BooleanField(default=False, verbose_name='Requer Carroceria Graneleira')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_items', to='cargo.cargotype', verbose_name='Tipo de Carga')),
                ('freight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='freight.freightorder', verbose_name='Ordem de Frete')),
            ],
            options={
                'verbose_name': 'Item de Carga',
                'verbose_name_plural': 'Itens de Cargas',
            },
        ),
    ]
