# Generated by Django 4.2.30 on 2026-05-30 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual')),
                ('responsible_name', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('responsible_phone', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('billing_address', models.TextField(verbose_name='Endereço de Faturamento')),
                ('operational_address', models.TextField(verbose_name='Endereço Operacional')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', max_length=15, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Proprietário')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa (PJ)',
                'verbose_name_plural': 'Perfis de Empresas (PJ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarrierCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=50, verbose_name='Inscrição Estadual')),
                ('responsible_name', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('responsible_phone', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('billing_address', models.TextField(verbose_name='Endereço de Faturamento')),
                ('operational_address', models.TextField(verbose_name='Endereço Operacional')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', max_length=15, verbose_name='Status')),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_company', to=settings.AUTH_USER_MODEL, verbose_name='Dono da Transportadora')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['-created_at'],
            },
        ),
    ]
