# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estimated_arrival_time', models.DateTimeField(verbose_name='Previsão de Chegada Estimada')),
                ('remaining_distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Distância Restante (KM)')),
                ('remaining_duration_minutes', models.PositiveIntegerField(verbose_name='Duração Restante (Minutos)')),
                ('average_speed_kmh', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='Velocidade Média (KM/H)')),
                ('reason', models.CharField(default='inicialização', max_length=255, verbose_name='Motivo do Recálculo')),
            ],
            options={
                'verbose_name': 'Registro de ETA',
                'verbose_name_plural': 'Registros de ETAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
