# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eta', '0001_initial'),
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etarecord',
            name='freight_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_records', to='freight.freightorder', verbose_name='Ordem de Frete'),
        ),
    ]
