# Generated by Django 4.2.30 on 2026-05-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('document_type', models.CharField(choices=[('CNH', 'Carteira Nacional de Habilitação'), ('CRLV', 'Certificado de Registro e Licenciamento do Veículo'), ('INVOICE', 'Nota Fiscal da Carga'), ('WEIGHING', 'Ticket de Pesagem')], max_length=20, verbose_name='Tipo do Documento')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=15, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do Documento')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
