# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Intermediação')),
                ('driver_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Repassado ao Motorista')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status do Pagamento')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('card', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário'), ('invoice', 'Faturamento / Fatura (PJ)')], default='pix', max_length=15, verbose_name='Método de Pagamento')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Transação Financeira')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Beneficiário')),
                ('freight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='freight.freightorder', verbose_name='Ordem de Frete')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Pagador')),
            ],
            options={
                'verbose_name': 'Pagamento de Frete',
                'verbose_name_plural': 'Pagamentos de Fretes',
                'ordering': ['-created_at'],
            },
        ),
    ]
