# Generated by Django 4.2.30 on 2026-05-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(max_length=20, unique=True, verbose_name='RENAVAM')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('vehicle_type', models.CharField(choices=[('SMALL_UTILITY', 'Utilitário Pequeno'), ('PICKUP', 'Picape / Caminhonete'), ('FIORINO', 'Fiorino / Furgão Pequeno'), ('VAN', 'Van de Carga'), ('LIGHT_TRUCK', 'Caminhão Leve (3/4)'), ('MEDIUM_TRUCK', 'Caminhão Médio (Toco)'), ('TRUCK', 'Caminhão Pesado (Truck)'), ('BOX_TRUCK', 'Caminhão Baú'), ('SIDER_TRUCK', 'Caminhão Sider'), ('GRAIN_TRUCK', 'Caminhão Graneleiro'), ('GRAIN_TRAILER', 'Carreta Graneleira (LS)'), ('GRAIN_BITREM', 'Bitrem Graneleiro'), ('GRAIN_RODOTREM', 'Rodotrem Graneleiro'), ('GRAIN_DUMP_TRUCK', 'Caçamba / Truck Basculante')], max_length=30, verbose_name='Tipo de Veículo')),
                ('body_type', models.CharField(choices=[('BOX', 'Baú (Fechado)'), ('OPEN', 'Grade Aberta'), ('SIDER', 'Sider (Lona Lateral)'), ('GRAIN', 'Graneleiro (Com Fominha)'), ('DUMP', 'Caçamba (Basculante)'), ('PLATFORM', 'Prancha / Plataforma'), ('REFRIGERATED', 'Frigorífico / Refrigerado')], max_length=30, verbose_name='Tipo de Carroceria')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Capacidade de Peso (KG)')),
                ('max_volume_m3', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacidade de Volume (M³)')),
                ('allowed_cargo_types', models.JSONField(blank=True, default=list, verbose_name='Tipos de Carga Permitidos')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Possui Seguro')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='Número da Apólice de Seguro')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', max_length=15, verbose_name='Status')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Atual')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Atual')),
                ('carrier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='companies.carriercompany', verbose_name='Transportadora')),
                ('owner_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Proprietário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
