# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('distance_to_pickup_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distância até Coleta (KM)')),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score de Compatibilidade')),
                ('proximity_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score de Proximidade')),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score de Avaliação')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Final de Matching')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('notified', 'Notificado'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Status da Candidatura')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_candidacies', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Candidato')),
                ('freight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='freight.freightorder', verbose_name='Ordem de Frete')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_candidacies', to='vehicles.vehicle', verbose_name='Veículo Utilizado')),
            ],
            options={
                'verbose_name': 'Candidato de Matching',
                'verbose_name_plural': 'Candidatos de Matching',
                'ordering': ['-final_score'],
            },
        ),
    ]
