# Generated by Django 4.2.30 on 2026-05-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cnh_number', models.CharField(max_length=20, verbose_name='Número da CNH')),
                ('cnh_category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=5, verbose_name='Categoria da CNH')),
                ('cnh_expiration_date', models.DateField(verbose_name='Validade da CNH')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, max_length=5, verbose_name='Avaliação do Motorista')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('suspended', 'Suspenso')], default='pending', max_length=15, verbose_name='Status')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Atual')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Atual')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('accepts_equipment', models.BooleanField(default=True, verbose_name='Transporta Equipamentos / Móveis')),
                ('accepts_dry_grains', models.BooleanField(default=False, verbose_name='Transporta Grãos Secos')),
                ('pix_key', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('bank_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Bancários')),
                ('carrier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='companies.carriercompany', verbose_name='Transportadora Vinculada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Motorista',
                'verbose_name_plural': 'Perfis de Motoristas',
                'ordering': ['-created_at'],
            },
        ),
    ]
