# Generated by Django 4.2.30 on 2026-05-31 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.CharField(choices=[('atraso', 'Atraso na Entrega'), ('carga_danificada', 'Carga Danificada / Avaria'), ('pagamento', 'Problema com Pagamento'), ('documento', 'Problema com Documentação'), ('motorista', 'Problema com Motorista'), ('cliente', 'Problema com Cliente'), ('divergencia_peso', 'Divergência de Peso / Volume'), ('cancelamento', 'Problema com Cancelamento'), ('problema_tecnico', 'Instabilidade / Problema Técnico'), ('outro', 'Outros Assuntos')], default='outro', max_length=30, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=15, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Atendimento'), ('waiting_user', 'Aguardando Usuário'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição do Chamado')),
                ('created_from', models.CharField(choices=[('portal', 'Portal Web'), ('app', 'Aplicativo Mobile'), ('ai', 'Assistente de IA'), ('admin', 'Painel Administrativo')], default='portal', max_length=15, verbose_name='Origem de Criação')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atendente Responsável')),
                ('freight_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='freight.freightorder', verbose_name='Ordem de Frete Relacionada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
