# Generated by Django 4.2.30 on 2026-05-31 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefone')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='Empresa / Organização')),
                ('profile_type', models.CharField(choices=[('investor', 'Investidor'), ('carrier', 'Transportadora'), ('shipper', 'Embarcador'), ('partner', 'Parceiro Comercial'), ('press', 'Imprensa'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Perfil do Lead')),
                ('estimated_interest_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('strategic', 'Estratégico')], default='medium', max_length=20, verbose_name='Nível de Interesse Estimado')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensagem / Comentário')),
                ('source_page', models.CharField(default='/', max_length=255, verbose_name='Página de Origem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('meeting_scheduled', 'Reunião Agendada'), ('negotiating', 'Em Negociação'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=30, verbose_name='Status de Atendimento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas de Acompanhamento Interno')),
            ],
            options={
                'verbose_name': 'Lead Comercial / Investidor',
                'verbose_name_plural': 'Leads Comerciais / Investidores',
                'ordering': ['-created_at'],
            },
        ),
    ]
