# Generated by Django 4.2.30 on 2026-05-31 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(choices=[('order_created', 'Pedido Criado'), ('driver_accepted', 'Motorista Aceitou'), ('driver_arrived_origin', 'Motorista Chegou à Origem'), ('cargo_collected', 'Carga Coletada'), ('route_started', 'Rota Iniciada'), ('location_updated', 'Localização Atualizada'), ('stop_detected', 'Parada Detectada'), ('route_deviation', 'Desvio de Rota'), ('risk_area_entered', 'Entrada em Área de Risco'), ('arrived_destination', 'Chegada ao Destino'), ('delivery_confirmed', 'Entrega Confirmada'), ('occurrence_registered', 'Ocorrência Registrada')], default='location_updated', max_length=50, verbose_name='Tipo do Evento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidade (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Direção (Graus)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.FileField(blank=True, null=True, upload_to='tracking/photos/%Y/%m/%d/', verbose_name='Foto da Ocorrência / Comprovante')),
                ('signature', models.FileField(blank=True, null=True, upload_to='tracking/signatures/%Y/%m/%d/', verbose_name='Assinatura Digital')),
                ('previous_status', models.CharField(blank=True, max_length=30, verbose_name='Status Anterior')),
                ('new_status', models.CharField(blank=True, max_length=30, verbose_name='Novo Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracking_events', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_tracking_events', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('freight_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='freight.freightorder', verbose_name='Ordem de Frete')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tracking_events', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Evento de Rastreamento',
                'verbose_name_plural': 'Eventos de Rastreamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
