# Generated by Django 4.2.30 on 2026-05-31 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('channel', models.CharField(choices=[('web', 'Portal Web'), ('mobile', 'Aplicativo Mobile'), ('admin', 'Painel Administrativo'), ('driver_app', 'App do Motorista'), ('carrier_portal', 'Portal da Transportadora')], default='web', max_length=25, verbose_name='Canal de Origem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Fechado'), ('escalated', 'Escalonado para Humano')], default='active', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conversa com IA',
                'verbose_name_plural': 'Conversas com IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Artigo')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('content', models.TextField(verbose_name='Conteúdo do Artigo')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='published', max_length=15, verbose_name='Status de Publicação')),
            ],
            options={
                'verbose_name': 'Artigo de Conhecimento',
                'verbose_name_plural': 'Artigos de Conhecimento',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('embedding_vector', models.JSONField(blank=True, default=list, verbose_name='Vetor de Embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados do Fragmento')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai_assistant.knowledgedocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Embedding de Conhecimento',
                'verbose_name_plural': 'Embeddings de Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sender', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente IA'), ('system', 'Sistema'), ('human_agent', 'Atendente Humano')], max_length=20, verbose_name='Remetente')),
                ('message_text', models.TextField(verbose_name='Texto da Mensagem')),
                ('intent', models.CharField(blank=True, max_length=100, verbose_name='Intenção Identificada')),
                ('confidence_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5, verbose_name='Confiança da Intenção')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados da Resposta')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem da Conversa',
                'verbose_name_plural': 'Mensagens da Conversa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('action_type', models.CharField(max_length=100, verbose_name='Tipo de Ação')),
                ('target_entity', models.CharField(blank=True, max_length=100, verbose_name='Entidade Alvo')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Alvo')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Confirmação'), ('confirmed', 'Confirmado pelo Usuário'), ('executed', 'Executado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status da Ação')),
                ('requires_confirmation', models.BooleanField(default=True, verbose_name='Exige Confirmação')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai_assistant.aiconversation', verbose_name='Conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions_triggered', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ação da IA',
                'verbose_name_plural': 'Ações da IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
