# Generated by Django 4.2.30 on 2026-05-30 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Carga')),
                ('category', models.CharField(choices=[('EQUIPMENTS', 'Equipamentos e Móveis'), ('DRY_GRAINS', 'Grãos Secos')], max_length=30, verbose_name='Categoria Principal')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Carga',
                'verbose_name_plural': 'Tipos de Cargas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CargoRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('recommended_vehicle_types', models.JSONField(default=list, verbose_name='Tipos de Veículos Recomendados')),
                ('required_body_types', models.JSONField(default=list, verbose_name='Tipos de Carrocerias Exigidas')),
                ('requires_covered_vehicle', models.BooleanField(default=False, verbose_name='Exige Veículo Coberto / Baú')),
                ('requires_grain_body', models.BooleanField(default=False, verbose_name='Exige Carroceria Graneleira')),
                ('requires_helper_recommended', models.BooleanField(default=False, verbose_name='Recomenda Ajudante')),
                ('requires_insurance_recommended', models.BooleanField(default=False, verbose_name='Recomenda Seguro de Carga')),
                ('requires_lashing', models.BooleanField(default=False, verbose_name='Exige Amarração de Carga')),
                ('requires_tarp', models.BooleanField(default=False, verbose_name='Exige Cobertura com Lona')),
                ('requires_invoice', models.BooleanField(default=False, verbose_name='Exige Nota Fiscal')),
                ('requires_weighing', models.BooleanField(default=False, verbose_name='Exige Pesagem em Balança')),
                ('handling_instructions', models.TextField(blank=True, verbose_name='Instruções de Manuseio')),
                ('cargo_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='cargo.cargotype', verbose_name='Tipo de Carga')),
            ],
            options={
                'verbose_name': 'Regra de Carga',
                'verbose_name_plural': 'Regras de Cargas',
            },
        ),
    ]
