# Generated by Django 4.2.30 on 2026-05-30 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('freight_requested', 'Frete Solicitado'), ('driver_found', 'Motorista Encontrado'), ('driver_accepted', 'Motorista Aceitou o Frete'), ('arrived_origin', 'Motorista Chegou na Coleta'), ('cargo_collected', 'Carga Coletada'), ('in_transit', 'Carga em Trânsito'), ('eta_updated', 'Previsão ETA Alterada'), ('delivered', 'Entrega Realizada'), ('payment_confirmed', 'Pagamento Confirmado'), ('alert', 'Alerta Operacional')], default='alert', max_length=30, verbose_name='Tipo da Notificação')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados da Notificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
    ]
